default: &default
  adapter: postgresql
  encoding: unicode
  username: ubuntu
  pool: 5

development:
  <<: *default
  database: Website_development

test:
  <<: *default
  database: Website_test

production:
  <<: *default
  database: Website_production
  password: <%= ENV['WEBSITE_DATABASE_PASSWORD'] %>
